### ISSUE TITLE
Feedback on Second Submission

### ISSUE THREAD

**Issue by Anisha7** [Sukhrobjon/CS-1.3-Challenges#2]
Good job on completing your second coding challenge. Here's some feedback to improve:
- To further challenge yourself, try implementing an alternative hash collision strategy, a  double-ended queue, or a circular buffer.
- Your medium post is incomplete. You need a minimum of 800 words for full credit.

**Comment by Sukhrobjon** [comment]
Thank you for your feedback. I will finalize my article.
